# Comprehensive NumPy Education

This notebook will take you from the basics to advanced topics in `NumPy`, with detailed explanations and examples.

## Table of Contents
1. [Introduction to NumPy](#introduction-to-numpy)
2. [Array Creation](#array-creation)
3. [Array Operations](#array-operations)
4. [Indexing and Slicing](#indexing-and-slicing)
5. [Broadcasting](#broadcasting)
6. [Mathematical and Statistical Functions](#mathematical-and-statistical-functions)
7. [Linear Algebra Operations](#linear-algebra-operations)
8. [Random Number Generation](#random-number-generation)
9. [Memory Management and Performance](#memory-management-and-performance)
10. [File I/O and Data Persistence](#file-io-and-data-persistence)
11. [Advanced Applications and Use Cases](#advanced-applications-and-use-cases)
12. [Exercises](#exercises)

## Introduction to NumPy

`Numpy` (Numerical Python) is a fundamental library for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures.

In [1]:
import numpy as np

## Array Creation

In [5]:
array_1d = np.array([1,2,3,4,5])
print("1D Array:",array_1d)

array_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
zeros_array = np.zeros((2,3))
print("Zeros Array:\n",zeros_array)

ones_array = np.ones((3,2))
print("Ones Array:\n",ones_array)

range_array = np.arange(10)
print("Range Array:",range_array)

linspace_array = np.linspace(0,1,5)
print("Linspace Array:",linspace_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range Array: [0 1 2 3 4 5 6 7 8 9]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [11]:
custom_dtype_array = np.array([(1,2.0,"Hello"),(3,4.5,"World")],dtype=[("id","i4"),("value","f4"),("text","U10")])
print("Custom Data Type Array:\n",custom_dtype_array)

Custom Data Type Array:
 [(1, 2. , 'Hello') (3, 4.5, 'World')]


## Array Operations

In [15]:
array = np.array([1,2,3,4])
sum_array = array +10
print("Sum Array",sum_array)

prod_array = array*2
print("Product Array:",prod_array)

Sum Array [11 12 13 14]
Product Array: [2 4 6 8]


In [16]:
mean_value = np.mean(array)
median_value = np.median(array)
std_dev_value = np.std(array)

print("Mean:", mean_value)
print("Median:",median_value)
print("Standard Deviation",std_dev_value)

Mean: 2.5
Median: 2.5
Standard Deviation 1.118033988749895


In [17]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
sum_all = np.sum(array_2d)
min_value = np.min(array_2d)
max_value = np.max(array_2d)

print("Sum of all elements:", sum_all)
print("Min value:", min_value)
print("Max value:", max_value)

Sum of all elements: 21
Min value: 1
Max value: 6


## Indexing and Slicing

In [19]:
slice_1d = array[1:4]
print("Sliced 1D Array:", slice_1d)

slice_2d = array_2d[:,1] # Take all rows and column 1
print("2D Array:\n",array_2d)
print("Sliced 2D Array:\n", slice_2d)

Sliced 1D Array: [2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
Sliced 2D Array:
 [2 5]


In [20]:
array_mask = array > 2
filtered_array = array[array_mask] # Use a boolean filter

print("Filtered Array:",filtered_array)

Filtered Array: [3 4]


In [21]:
indices = [1, 3]
fancy_indexed_array = array[indices] # Just take 1 and 3 indexes
print("Fancy Indexed Array:", fancy_indexed_array)

Fancy Indexed Array: [2 4]


## Broadcasting

In [24]:
array = np.array([[1,2,3],[4,5,6]])
scalar = 10
brodcasted_array = array + scalar
print("Broadcasted Array:\n",brodcasted_array)

Brodcasted Array:
 [[11 12 13]
 [14 15 16]]


In [33]:
array2 = np.array([[10, 20, 30], [40, 50, 60]])
broadcasted_array2 = array + array2
print("Broadcasted Array with Another Array:\n", broadcasted_array2)

Broadcasted Array with Another Array:
 [[11 22 33]
 [44 55 66]]


In [34]:
array3 = np.array([[40, 50, 60]])
broadcasted_array3 = array + array3
print("Broadcasted Array with Another Array:\n", broadcasted_array3)

Broadcasted Array with Another Array:
 [[41 52 63]
 [44 55 66]]


## Mathematical and Statistical Functions

In [37]:
array = np.array([1,2,3])
log_array = np.log(array)
sin_array = np.sin(array)

print("Logarithmic Values:\n",log_array)
print("Sine Values:\n", sin_array)

Logarithmic Values:
 [0.         0.69314718 1.09861229]
Sine Values:
 [0.84147098 0.90929743 0.14112001]


In [40]:
data = np.random.randn(1000)
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 0.016403563913661674
Median: 0.013123890422853234
Variance: 1.0027113297759271
Standard Deviation: 1.0013547472179514


## Linear Algebra Operations

In [41]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

matrix_product = np.matmul(matrix_a,matrix_b)
print("Matrix Product:\n",matrix_product)

Matrix Product:
 [[19 22]
 [43 50]]


In [42]:
# Singular Value Decomposition (SVD)
u,s,vh = np.linalg.svd(matrix_a)

print("U:\n", u)
print("S:\n", s)
print("VH:\n", vh)

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S:
 [5.4649857  0.36596619]
VH:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [43]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Random Number Generation

In [44]:
sample = np.random.choice([1,2,3,4,5],size = 10,replace= True)
print("Random Sample:",sample)

Random Sample: [3 4 1 4 5 5 2 1 3 4]


In [58]:
normal_dist = np.random.normal(loc=0,scale=1,size=1000)
uniform_dist = np.random.uniform(low=0,high=10,size=1000)

print("Normal Distribution Mean:", np.mean(normal_dist))
print("Uniform Distribution Mean:", np.mean(uniform_dist))

Normal Distribution Mean: 0.013541073631714043
Uniform Distribution Mean: 4.992341748453319


## Memory Management and Performance

In [62]:
array_large = np.random.rand(10000, 10000)
print("Memory usage of large array:", array_large.nbytes / (1024 ** 2), "MB")

Memory usage of large array: 762.939453125 MB


In [63]:
# Performance comparison
import time

start_time = time.time()
_ = np.dot(matrix_a, matrix_b)
end_time = time.time()
print("Time taken for matrix multiplication:", end_time - start_time, "seconds")

Time taken for matrix multiplication: 0.0009996891021728516 seconds


## File I/O and Data Persistence

In [64]:
np.save("array_file.npy",array)
loaded_array = np.load("array_file.npy")
print("Loaded Array:\n", loaded_array)

Loaded Array:
 [1 2 3]


In [65]:
np.savetxt("array_file.txt",array_2d,fmt="%d")
text_loaded_array = np.loadtxt("array_file.txt")
print("Loaded Text Array:\n", text_loaded_array)

Loaded Text Array:
 [[1. 2. 3.]
 [4. 5. 6.]]


## Advanced Applications and Use Cases

In [ ]:
# Basic image manipulation (e.g., grayscale conversion)
from skimage import color,io

# Load an image
image = io.imread('path_to_image.jpg')  # Load image from file
gray_image = color.rgb2gray(image)  # Convert image to grayscale
print("Grayscale Image Shape:", gray_image.shape)  # Print shape of grayscale image

In [ ]:
import pandas as pd

# Load a dataset into a DataFrame
df = pd.read_csv('path_to_dataset.csv')  # Read CSV file into DataFrame
data_array = df.to_numpy()  # Convert DataFrame to NumPy array
print("Data Array:\n", data_array)

## Exercises
Here are some exercises to practice what you've learned.

Exercise 1: Array Operations
Create a 3x3 array of random numbers and perform element-wise addition and multiplication.

Exercise 2: Indexing and Slicing
Create a 4x4 matrix and extract the submatrix formed by the last two rows and columns.

Exercise 3: Broadcasting
Broadcast a 1D array of shape (3,) to a 2D array of shape (3, 4).

Exercise 4: Linear Algebra
Compute the determinant and inverse of a 2x2 matrix.